export const isLogged = state => state.isLogged
export const loginInfo = state => state.loginInfo
export const fanUnreadNum = state => state.fanUnreadNum
export const byLikeUnreadNum = state => state.byLikeUnreadNum
export const byCommentUnreadNum = state => state.byCommentUnreadNum
export const atNum = state => state.atNum
export const followedNewsNum = state => state.followedNewsNum
export const allPrivateLetter = state => state.allPrivateLetter
export const popularVideo = state => state.popularVideo
export const playList = state => state.playList
