export const isLogged = state => state.isLogged
export const loginInfo = state => state.loginInfo
export const followerList = state => state.followerList
export const fanList = state => state.fanList
export const likeList = state => state.likeList
export const videoList = state => state.videoList
export const followerNum = state => state.followerNum
export const fanNum = state => state.fanNum
export const likeNum = state => state.likeNum
export const videoNum = state => state.videoNum
export const popularVideo = state => state.popularVideo
